from __future__ import annotations

CATEGORY_DESCRIPTIONS = {
    "Swimming": "Lane swim, leisure swim, and water fitness.",
    "Racquet Sports": "Badminton, pickleball, tennis, squash, and table tennis.",
    "Team & Gym Sports": "Basketball, volleyball, dodgeball, open gym, and multi-sport sessions.",
    "Skating & Wheels": "Leisure skate, shinny, figure skating, roller skating, and roller hockey.",
    "Fitness & Workout": "Cardio, strength, HIIT, walking track, and workout room sessions.",
    "Yoga, Pilates & Wellness": "Yoga, Pilates, tai chi, qigong, and meditation.",
    "Dance": "Zumba, line dance, hip hop, ballroom, and other dance programs.",
    "Kids, Youth & Family": "Caregiver play, youth zones, clubs, and family-friendly programs.",
    "Arts & Crafts": "Visual arts, crafts, DIY, sewing, and maker-style programs.",
    "Music, Media & Performance": "Music, DJing, media arts, photography, drama, and performance.",
    "Games & Social": "Cards, board games, bingo, billiards, video games, and social recreation.",
    "Cooking, Learning & Life Skills": "Cooking, homework, study, debate, computers, and practical skills.",
    "Outdoor & Specialty Sports": "Soccer, baseball, cricket, archery, climbing, golf, and similar sports.",
}

ACTIVITY_TAXONOMY = {
    "Swimming": [
        "Adapted Leisure Swim",
        "Aquatic Fitness: Arthritis",
        "Aquatic Fitness: Boot Camp",
        "Aquatic Fitness: Circuit Training",
        "Aquatic Fitness: Deep",
        "Aquatic Fitness: Deep (Women)",
        "Aquatic Fitness: Kickboxing",
        "Aquatic Fitness: Mind Body",
        "Aquatic Fitness: Shallow",
        "Aquatic Fitness: Shallow (Women)",
        "Aquatic Fitness: Walking",
        "Aquatic Fitness: Water Walking",
        "Lane Swim",
        "Lane Swim (Men)",
        "Lane Swim (Women)",
        "Lane Swim: Limited Lanes",
        "Lane Swim: Long Course (50m)",
        "Lane Swim: Older Adult",
        "Lane Swim: Quiet (No Music)",
        "Lane Swim: Short Course (25m)",
        "Leisure Swim",
        "Leisure Swim (Men)",
        "Leisure Swim (Women)",
        "Leisure Swim: Adapted",
        "Leisure Swim: Adult",
        "Leisure Swim: Adult (Therapeutic Time)",
        "Leisure Swim: Family",
        "Leisure Swim: Older Adult",
        "Leisure Swim: Open and Inclusive",
        "Leisure Swim: Preschool",
        "Leisure Swim: Youth",
    ],
    "Racquet Sports": [
        "Badminton",
        "Badminton (Women)",
        "Badminton - Court",
        "Badminton with Caregiver",
        "Badminton with Family",
        "Pickleball",
        "Pickleball (Women)",
        "Pickleball with Family",
        "Squash",
        "Table Tennis",
        "Table Tennis (Women)",
        "Table Tennis with Family",
        "Tennis",
    ],
    "Team & Gym Sports": [
        "Ball Hockey",
        "Ball Hockey: Recreational",
        "Basketball",
        "Basketball (Girls)",
        "Basketball (Men)",
        "Basketball (Women)",
        "Basketball with Family",
        "Dodgeball",
        "Dodgeball (2SLGBTQ+)",
        "Multi-Sport",
        "Multi-Sport (Girls)",
        "Multi-Sport (Girls) TWEENS",
        "Multi-Sport (Women)",
        "Multi-Sport with Family",
        "Netball",
        "Open Gym",
        "Open Gym (Women)",
        "Open Gym With Family",
        "Open Gym with Caregiver",
        "Open Gym with Family",
        "Parasport: Wheelchair Basketball",
        "Volleyball",
        "Volleyball (Female Only)",
    ],
    "Skating & Wheels": [
        "Adapted Leisure Skate with Family",
        "Figure Skating",
        "Figure Skating (unsupervised)",
        "Leisure Skate",
        "Leisure Skate (Unsupervised)",
        "Leisure Skate: Adult",
        "Leisure Skate: Adult (Unsupervised)",
        "Leisure Skate: Child with Caregiver",
        "Leisure Skate: Child with Caregiver (Unsupervised)",
        "Leisure Skate: Older Adult",
        "Leisure Skate: Older Adult (Unsupervised)",
        "Leisure Skate: Youth",
        "Roller Hockey",
        "Roller Skate: Adults",
        "Roller Skate: Child with Caregiver",
        "Roller Skate: Older Adults",
        "Shinny (Women)",
        "Shinny: Adult",
        "Shinny: Adult (Unsupervised)",
        "Shinny: Child",
        "Shinny: Child (Girls)",
        "Shinny: Child with Caregiver",
        "Shinny: Older Adult (Unsupervised)",
        "Shinny: Older Adult (Women) (Unsupervised)",
        "Shinny: Youth",
        "Shinny: Youth (Girls)",
    ],
    "Fitness & Workout": [
        "Cardio Dance",
        "Cardio Dance: Afro and Soca Fusion",
        "Cardio Dance: Bollywood",
        "Cardio: Dance",
        "Cardio: High/Low",
        "Cardio: Kickboxing",
        "Cardio: Rebounder",
        "Cycle Fit",
        "Functional Fit",
        "Gentle Fit",
        "Gentle Fit (Women)",
        "HIIT: Balance Ball",
        "HIIT: Boot Camp",
        "Mobility and Strength: Chair",
        "Osteo Fit",
        "Pedal and Strength",
        "Step",
        "Strength & Conditioning",
        "Strength and Conditioning",
        "Strength and Conditioning (Women)",
        "Walk Fit",
        "Walking",
        "Walking/Running Track",
        "Walking/Running Track (Women)",
        "Weight/Cardio Room",
        "Weight/Cardio Room (Women)",
        "Weight/Cardio Room: Physical Therapy",
    ],
    "Yoga, Pilates & Wellness": [
        "Meditation",
        "Pilates",
        "Pilates (Women)",
        "Pilates with Baby",
        "Pilates: Chair",
        "Qigong",
        "Tai Chi",
        "Yoga",
        "Yoga (Women)",
        "Yoga Chair",
        "Yoga with Baby",
        "Yoga/Pilates Fusion",
        "Yoga: Chair",
    ],
    "Dance": [
        "Collaboration: Kiki Ballroom Program",
        "Collaboration: Learn to Vogue - Advanced",
        "Collaboration: Learn to Vogue - Beginner",
        "Dance: Ballroom",
        "Dance: Basics",
        "Dance: Breakdance",
        "Dance: Clogging",
        "Dance: Hawaiian",
        "Dance: Hip Hop",
        "Dance: Latin",
        "Dance: Line Dance",
        "Dance: Line Dance - Advanced",
        "Dance: Line Dance - Sequence",
        "Dance: Line Dance - Social",
        "Dance: STOMP",
        "Dance: Social",
        "Dance: Urban",
        "Ice Breakdancing",
        "Zumba",
        "Zumba Gold®",
        "Zumba®",
        "Zumba® (Women)",
    ],
    "Kids, Youth & Family": [
        "Anime Club: Youth",
        "Club (Boys)",
        "Club (Girls)",
        "Club: Homework",
        "Club: Social",
        "Collaboration: Pro Action Cops and Kids",
        "Indoor Playground with Caregiver",
        "Level Up - Drop In Lessons (Youth)",
        "Open Space",
        "Recreation Adventures with Caregiver",
        "Recreation Discovery with Caregiver",
        "Recreation Fun and Play With Caregiver",
        "Recreation Fun and Play with Caregiver",
        "Tween Zone",
        "Young Men & Women's Program",
        "Young Men's Program",
        "Young Women's Program",
        "Youth Council",
        "Youth Leadership Program",
        "Youth Zone",
    ],
    "Arts & Crafts": [
        "Art Club",
        "Artist in the 6ix",
        "Bazaar Crafts",
        "Bunka",
        "Colouring",
        "Country Crafts",
        "Crochet",
        "Decoupage",
        "DIY: Canvas",
        "DIY: Design",
        "DIY: Event Planning 101",
        "DIY: Health and Wellness",
        "DIY: Visual Arts",
        "Drawing and Painting",
        "Jewellery Making",
        "Knitting",
        "Multi Arts",
        "Multi Arts With Family",
        "Multi Arts with Family",
        "Painting",
        "Painting: Mixed Media",
        "Quilting",
        "Sewing",
        "Stained Glass",
        "The Maker's Space",
        "Wood Carving",
    ],
    "Music, Media & Performance": [
        "AMPED Art of DJing",
        "AMPED Art of Djing",
        "AMPED Artist Development",
        "AMPED Music Engineering",
        "AMPED Photography/Videography",
        "Creative Writing",
        "Drag Open Studio (2SLGBTQ+)",
        "Drama",
        "Music: Band",
        "Music: Choir",
        "Music: Drumming - Drum Pads",
        "Music: Jam Session",
        "Music: Karaoke",
        "Open Mic",
        "Photography",
        "Workshop: Drag Masterclass",
    ],
    "Games & Social": [
        "Cards",
        "Cards: Bid Euchre",
        "Cards: Bridge Progressive",
        "Cards: Cribbage",
        "Cards: Duplicate Bridge",
        "Cards: Euchre",
        "Cards: Hand and Foot",
        "Games",
        "Games (Women)",
        "Games: Billiards",
        "Games: Bingo",
        "Games: Board",
        "Games: Chess",
        "Games: Darts",
        "Games: Dominoes",
        "Games: Dungeons & Dragons",
        "Games: Mahjong",
        "Games: Shuffleboard",
        "Games: Snooker",
        "Lunch Time",
        "Movie Time",
        "Tournament Time",
        "Virtual Driving Simulator",
        "Video Game Time",
    ],
    "Cooking, Learning & Life Skills": [
        "Chop It Like It's Hot!",
        "Computer Lab",
        "Cooking: Baking",
        "Hair: Braiding, Weaving and Wigs",
        "Study Time",
        "The Great Debate",
        "Workshop: Computers",
    ],
    "Outdoor & Specialty Sports": [
        "Archery",
        "Baseball",
        "Bocce",
        "Bocce (Women)",
        "Carpet Bowling",
        "Cricket",
        "Golf",
        "Lacrosse",
        "Lawn Bowling",
        "Rock Wall Climbing",
        "Skateboarding",
        "Soccer",
        "Soccer (Women)",
        "Soccer with Family",
        "Ultimate",
    ],
}
