from __future__ import annotations

CATEGORY_DESCRIPTIONS = {
    "Swimming": "Lane swim, leisure swim, and water fitness.",
    "Racquet Sports": "Badminton, pickleball, tennis, squash, and table tennis.",
    "Team & Gym Sports": "Basketball, volleyball, dodgeball, open gym, and multi-sport sessions.",
    "Skating & Wheels": "Leisure skate, shinny, figure skating, roller skating, and roller hockey.",
    "Fitness & Workout": "Cardio, strength, HIIT, walking track, and workout room sessions.",
    "Yoga, Pilates & Wellness": "Yoga, Pilates, tai chi, qigong, and meditation.",
    "Dance": "Zumba, line dance, hip hop, ballroom, and other dance programs.",
    "Kids, Youth & Family": "Caregiver play, youth zones, clubs, and family-friendly programs.",
    "Arts & Crafts": "Visual arts, crafts, DIY, sewing, and maker-style programs.",
    "Music, Media & Performance": "Music, DJing, media arts, photography, drama, and performance.",
    "Games & Social": "Cards, board games, bingo, billiards, video games, and social recreation.",
    "Cooking, Learning & Life Skills": "Cooking, homework, study, debate, computers, and practical skills.",
    "Outdoor & Specialty Sports": "Soccer, baseball, cricket, archery, climbing, golf, and similar sports.",
}

ACTIVITY_TAXONOMY = {
    "Swimming": [
        "Adapted Leisure Swim",
        "Aquatic Fitness: Arthritis",
        "Aquatic Fitness: Boot Camp",
        "Aquatic Fitness: Circuit Training",
        "Aquatic Fitness: Deep",
        "Aquatic Fitness: Kickboxing",
        "Aquatic Fitness: Mind Body",
        "Aquatic Fitness: Shallow",
        "Aquatic Fitness: Walking",
        "Aquatic Fitness: Water Walking",
        "Lane Swim",
        "Leisure Swim",
    ],
    "Racquet Sports": [
        "Badminton",
        "Pickleball",
        "Squash",
        "Table Tennis",
        "Tennis",
    ],
    "Team & Gym Sports": [
        "Ball Hockey",
        "Basketball",
        "Dodgeball",
        "Multi-Sport",
        "Netball",
        "Open Gym",
        "Volleyball",
        "Wheelchair Basketball",
    ],
    "Skating & Wheels": [
        "Adapted Leisure Skate",
        "Figure Skating",
        "Leisure Skate",
        "Roller Hockey",
        "Roller Skating",
        "Shinny",
    ],
    "Fitness & Workout": [
        "Cardio Dance",
        "Cardio Dance: Afro and Soca Fusion",
        "Cardio Dance: Bollywood",
        "Cardio: High/Low",
        "Cardio: Kickboxing",
        "Cardio: Rebounder",
        "Cycle Fit",
        "Functional Fit",
        "Gentle Fit",
        "HIIT",
        "Mobility & Strength",
        "Osteo Fit",
        "Pedal and Strength",
        "Step",
        "Strength and Conditioning",
        "Walk Fit",
        "Walking",
        "Walking / Running Track",
        "Weight / Cardio Room",
    ],
    "Yoga, Pilates & Wellness": [
        "Meditation",
        "Pilates",
        "Qigong",
        "Tai Chi",
        "Yoga",
        "Yoga / Pilates",
    ],
    "Dance": [
        "Argentine Tango",
        "Ballroom Dance",
        "Breakdance",
        "Clogging",
        "Dance Basics",
        "Hawaiian Dance",
        "Hip Hop Dance",
        "Kiki Ballroom",
        "Latin Dance",
        "Line Dance",
        "Social Dance",
        "Stomp",
        "Urban Dance",
        "Vogue",
        "Zumba",
    ],
    "Kids, Youth & Family": [
        "After School Club",
        "Eco Explorer Club",
        "Indoor Playground",
        "Level Up Lessons",
        "Open Space",
        "Pro Action Cops and Kids",
        "Pro Action Hockey",
        "Anime Club",
        "Recreation Adventures",
        "Recreation Discovery",
        "Recreation Fun and Play",
        "Special Event",
        "Tween Zone",
        "Walking & Social Club",
        "Young Men's / Women's Program",
        "Young Men's Program",
        "Young Women's Multi-Sport",
        "Young Women's Program",
        "Youth Club",
        "Youth Council",
        "Youth Leadership Program",
        "Youth Zone",
    ],
    "Arts & Crafts": [
        "Art Club",
        "Artist in the 6ix",
        "Bazaar Crafts",
        "Bunka",
        "Colouring",
        "Country Crafts",
        "Crafty Creations",
        "Crochet",
        "Decoupage",
        "DIY / Maker",
        "Drawing",
        "Drawing and Painting",
        "Jewellery Making",
        "Knitting",
        "Maker Space",
        "Multi Arts",
        "Painting",
        "Paper Tole",
        "Quilting",
        "Sewing",
        "Stained Glass",
        "Wood Carving",
    ],
    "Music, Media & Performance": [
        "Artist Development",
        "Band",
        "Choir",
        "Creative Writing",
        "DJing",
        "Drag Masterclass",
        "Drag Open Studio",
        "Drama",
        "Drum Circle",
        "Drumming",
        "Jam Session",
        "Karaoke",
        "Media Arts",
        "Music Engineering",
        "Open Mic",
        "Photography",
        "Photography & Videography",
        "Storytelling",
    ],
    "Games & Social": [
        "Adapted Social Night",
        "Bid Euchre",
        "Billiards",
        "Bingo",
        "Board & Video Games",
        "Board Games",
        "Cards",
        "Chess",
        "Cornhole",
        "Cribbage",
        "Darts",
        "Dominoes",
        "Dungeons & Dragons",
        "Euchre",
        "Euchre Progressive",
        "Game Time",
        "Games",
        "Hand and Foot",
        "Lunch Program",
        "Lunch Time",
        "Mahjong",
        "Movie Night",
        "Shuffleboard",
        "Snooker",
        "Social Club",
        "Tournament Time",
        "Virtual Driving Simulator",
        "Video Game Time",
    ],
    "Cooking, Learning & Life Skills": [
        "Baking",
        "Chop It Like It's Hot!",
        "Computer Lab",
        "Cooking Time",
        "Event Planning 101",
        "Great Debate",
        "Hair: Braiding, Weaving and Wigs",
        "Homework Club",
        "Study Time",
    ],
    "Outdoor & Specialty Sports": [
        "Archery",
        "Baseball",
        "Bocce",
        "Carpet Bowling",
        "Cricket",
        "Golf",
        "Lacrosse",
        "Lawn Bowling",
        "Rock Wall Climbing",
        "Skateboarding",
        "Soccer",
        "Ultimate",
    ],
}
