from __future__ import annotations

CATEGORY_DESCRIPTIONS = {
    "Swimming": "Lane swim, leisure swim, and water fitness.",
    "Fitness & Workout": "Cardio, strength, HIIT, walking track, and workout room sessions.",
    "Racquet Sports": "Badminton, pickleball, tennis, squash, and table tennis.",
    "Team & Gym Sports": "Basketball, volleyball, dodgeball, open gym, and multi-sport sessions.",
    "Yoga, Pilates & Wellness": "Yoga, Pilates, tai chi, qigong, and meditation.",
    "Family / Caregiver": "Family-friendly, caregiver-supported, and parent-and-child recreation programs.",
    "Games & Social": "Cards, board games, bingo, billiards, video games, and social recreation.",
    "Kids & Youth": "Youth zones, clubs, drop-in lessons, and youth-focused recreation.",
    "Outdoor & Specialty Sports": "Soccer, baseball, cricket, archery, climbing, golf, and similar sports.",
    "Dance": "Zumba, line dance, hip hop, ballroom, and other dance programs.",
    "Cooking, Learning & Life Skills": "Cooking, homework, study, debate, computers, and practical skills.",
    "Arts & Crafts": "Visual arts, crafts, DIY, sewing, and maker-style programs.",
    "Music, Media & Performance": "Music, DJing, media arts, photography, drama, and performance.",
    "Skating & Wheels": "Leisure skate, shinny, figure skating, roller skating, and roller hockey.",
}

ACTIVITY_TAXONOMY = {
    "Swimming": [
        "Adapted Leisure Swim",
        "Aquatic Fitness: Arthritis",
        "Aquatic Fitness: Boot Camp",
        "Aquatic Fitness: Circuit Training",
        "Aquatic Fitness: Deep",
        "Aquatic Fitness: Deep (Women)",
        "Aquatic Fitness: Kickboxing",
        "Aquatic Fitness: Mind Body",
        "Aquatic Fitness: Shallow",
        "Aquatic Fitness: Shallow (Giovanni Caboto)",
        "Aquatic Fitness: Shallow (Women)",
        "Aquatic Fitness: Walking",
        "Aquatic Fitness: Water Walking",
        "City Camp Swim",
        "Humber College Swim",
        "Lane Swim",
        "Lane Swim (Giovanni Caboto)",
        "Lane Swim (Men)",
        "Lane Swim (Women)",
        "Lane Swim: Long Course (50m)",
        "Lane Swim: Older Adult",
        "Lane Swim: Quiet (No Music)",
        "Lane Swim: Short Course (25m)",
        "Leisure Swim",
        "Leisure Swim (Giovanni Caboto)",
        "Leisure Swim (Men)",
        "Leisure Swim (Women)",
        "Leisure Swim - Outdoor Pool",
        "Leisure Swim: Adapted",
        "Leisure Swim: Adult",
        "Leisure Swim: Adult (Therapeutic Time)",
        "Leisure Swim: Older Adult",
        "Leisure Swim: Open and Inclusive",
        "Leisure Swim: Preschool",
        "Leisure Swim: Youth",
    ],
    "Fitness & Workout": [
        "Cardio Dance",
        "Cardio Dance: Afro and Soca Fusion",
        "Cardio Dance: Bollywood",
        "Cardio: High/Low",
        "Cardio: Kickboxing",
        "Cardio: Rebounder",
        "Cycle Fit",
        "Functional Fit",
        "Gentle Fit",
        "Gentle Fit (Gazebo)",
        "Gentle Fit - Low Impact",
        "Gus Ryder Health Club",
        "HIIT: Balance Ball",
        "HIIT: Boot Camp",
        "HIIT: Boot Camp (Gazebo)",
        "Mobility and Strength: Chair",
        "Open Fitness Studio",
        "Osteo Fit",
        "Outdoor Walk Fit",
        "Pedal and Strength",
        "Step",
        "Strength and Conditioning",
        "Strength and Conditioning (Gazebo)",
        "Strength and Conditioning (Women)",
        "Walk Fit",
        "Walking",
        "Walking/Running Track",
        "Walking/Running Track (Women)",
        "Weight/Cardio Room",
        "Weight/Cardio Room (Women)",
        "Weight/Cardio Room: Physical Therapy",
    ],
    "Racquet Sports": [
        "Badminton",
        "Badminton (Women)",
        "Badminton - Court",
        "Pickleball",
        "Pickleball (2SLGBTQ+)",
        "Pickleball (Women)",
        "Squash",
        "Table Tennis",
        "Table Tennis (Women)",
        "Tennis",
    ],
    "Team & Gym Sports": [
        "Ball Hockey",
        "Basketball",
        "Basketball (Adult)",
        "Basketball (Girls)",
        "Basketball (Men)",
        "Basketball (Women)",
        "Dodgeball",
        "Dodgeball (2SLGBTQ+)",
        "Multi-Sport",
        "Multi-Sport (Girls)",
        "Multi-Sport (Women)",
        "Netball",
        "Open Gym",
        "Open Gym (Women)",
        "Parasport: Wheelchair Basketball",
        "Volleyball",
        "Volleyball (2SLGBTQ+)",
        "Volleyball (Women)",
    ],
    "Yoga, Pilates & Wellness": [
        "Meditation",
        "Outdoor Tai Chi",
        "Pilates",
        "Pilates (Women)",
        "Pilates: Chair",
        "Qigong",
        "Tai Chi",
        "Yoga",
        "Yoga (Women)",
        "Yoga/Pilates Fusion",
        "Yoga: Chair",
    ],
    "Family / Caregiver": [
        "Adapted Leisure Skate with Family",
        "Badminton with Caregiver",
        "Badminton with Family",
        "Basketball with Family",
        "Family Garden Drop In",
        "Games: Board with Family",
        "Indoor Playground with Caregiver",
        "Lane Swim: Family",
        "Leisure Skate: Child with Caregiver",
        "Leisure Skate: Child with Caregiver (Unsupervised)",
        "Leisure Swim: Family",
        "Multi-Sport with Family",
        "Multi-Sport With Family (2SLGBTQ+)",
        "Multi Arts with Family",
        "Open Gym with Family",
        "Open Gym with Caregiver",
        "Pickleball with Family",
        "Recreation Fun and Play with Caregiver",
        "Recreation Fun and Play with Caregiver (Women)",
        "Shinny: Child with Caregiver",
        "Shinny: Early Years with Caregiver (Unsupervised)",
        "Soccer with Caregiver",
        "Soccer with Family",
        "Table Tennis with Family",
        "Yoga with Baby",
        "Yoga with Family",
    ],
    "Games & Social": [
        "Cards",
        "Cards (Women)",
        "Cards: Bid Euchre",
        "Cards: Bridge",
        "Cards: Bridge Open",
        "Cards: Bridge Progressive",
        "Cards: Bridge Team",
        "Cards: Cribbage",
        "Cards: Duplicate Bridge",
        "Cards: Euchre",
        "Cards: Euchre Progressive",
        "Cards: Hand and Foot",
        "Cornhole",
        "Games",
        "Games: Billiards",
        "Games: Bingo",
        "Games: Board",
        "Games: Chess",
        "Games: Darts",
        "Games: Dominoes",
        "Games: Dungeons & Dragons",
        "Games: Mahjong",
        "Games: Shuffleboard",
        "Games: Snooker",
        "Lunch Time",
        "Movie Time",
        "Tournament Time",
        "Virtual Driving Simulator",
        "Video Game Time",
    ],
    "Kids & Youth": [
        "Club (Boys & Girls)",
        "Club (Girls)",
        "Club: Homework",
        "Club: Reading",
        "Club: Social",
        "Collaboration: Pro Action Cops and Kids",
        "EYS-D: Tween Zone",
        "Level Up - Drop In Lessons (Youth)",
        "Open Space",
        "Tween Zone",
        "Water Play",
        "Young Men's Program",
        "Young Women's Program",
        "Youth Council",
        "Youth Leadership Program",
        "Youth Lifeguard Club",
        "Youth Zone",
    ],
    "Outdoor & Specialty Sports": [
        "Archery",
        "Baseball",
        "Bocce",
        "Bocce (Women)",
        "Carpet Bowling",
        "Cricket",
        "Golf",
        "Lawn Bowling",
        "Rock Wall Climbing",
        "Skateboarding",
        "Soccer",
        "Soccer (Women)",
        "Ultimate",
    ],
    "Dance": [
        "Collaboration: Kiki Ballroom Program",
        "Collaboration: Learn to Vogue - Advanced",
        "Collaboration: Learn to Vogue - Advanced (2SLGBTQ+)",
        "Collaboration: Learn to Vogue - Beginner",
        "Collaboration: Learn to Vogue - Beginner (2SLGBTQ+)",
        "Dance: Ballroom",
        "Dance: Basics",
        "Dance: Breakdance",
        "Dance: Caribbean",
        "Dance: Clogging",
        "Dance: Hawaiian",
        "Dance: Hip Hop",
        "Dance: Latin",
        "Dance: Line Dance",
        "Dance: Line Dance - Advanced",
        "Dance: Line Dance - Sequence",
        "Dance: Line Dance - Social",
        "Dance: STOMP",
        "Dance: STOMP (2SLGBTQ+)",
        "Dance: Social",
        "Ice Breakdancing",
        "Zumba Gold®",
        "Zumba®",
        "Zumba® (Women)",
    ],
    "Cooking, Learning & Life Skills": [
        "Chop It Like It's Hot!",
        "Computer Lab",
        "Cooking: Baking",
        "Hair: Braiding, Weaving and Wigs",
        "Study Time",
        "The Great Debate",
        "Workshop: Computers",
    ],
    "Arts & Crafts": [
        "Art Club",
        "Artist in the 6ix",
        "Bazaar Crafts",
        "Bunka",
        "Colouring",
        "Country Crafts",
        "Crochet",
        "Decoupage",
        "DIY: Art",
        "DIY: Canvas",
        "DIY: Design",
        "DIY: Event Planning 101",
        "DIY: Health and Wellness",
        "DIY: Visual Arts",
        "Drawing and Painting",
        "Drawing and Painting (Women)",
        "Jewellery Making",
        "Knitting",
        "Painting: Mixed Media",
        "Quilting",
        "Sewing",
        "Stained Glass",
        "Wood Carving",
    ],
    "Music, Media & Performance": [
        "AMPED Art of DJing",
        "AMPED Artist Development",
        "AMPED Music Engineering",
        "AMPED Photography/Videography",
        "Creative Writing",
        "Drag Masterclass (2SLGBTQ+)",
        "Drag Open Studio (2SLGBTQ+)",
        "Media Arts",
        "Music: Band",
        "Music: Choir",
        "Music: Drumming - Drum Pads",
        "Music: Karaoke",
        "Open Mic",
        "Photography",
    ],
    "Skating & Wheels": [
        "Figure Skating",
        "Leisure Skate",
        "Leisure Skate (Pride Skate)",
        "Leisure Skate: Adult",
        "Leisure Skate: Adult (Unsupervised)",
        "Leisure Skate: Older Adult (Unsupervised)",
        "Leisure Skate: Youth",
        "Pick Up Hockey: Adults",
        "Pick Up Hockey: Adults (Unsupervised)",
        "Pick Up Hockey: Older Adult",
        "Pick Up Hockey: Older Adult (Unsupervised)",
        "Roller Skating",
        "Shinny (Women)",
        "Shinny (Women) (Unsupervised)",
        "Shinny: Adult",
        "Shinny: Adult (Unsupervised)",
        "Shinny: Adult (Women)",
        "Shinny: Child",
        "Shinny: Child (Girls)",
        "Shinny: Older Adult (Unsupervised)",
        "Shinny: Older Adult (Women) (Unsupervised)",
        "Shinny: Youth",
        "Shinny: Youth (Girls)",
    ]
}

RAW_TO_CANONICAL_ACTIVITY = {
    "Open Gym with Family": "Open Gym with Family",
    "Open Gym With Family": "Open Gym with Family",
    "Multi Arts with Family": "Multi Arts with Family",
    "Multi Arts With Family": "Multi Arts with Family",
    "Recreation Fun and Play with Caregiver": "Recreation Fun and Play with Caregiver",
    "AMPED Art of DJing": "AMPED Art of DJing",
    "AMPED Art of Djing": "AMPED Art of DJing",
    "Cardio High/Low": "Cardio: High/Low",
    "Cardio: High/Low": "Cardio: High/Low",
    "Leisure Skate: Child with Caregiver (Unsupervised)": "Leisure Skate: Child with Caregiver (Unsupervised)",
    "Leisure Skate: Child with Caregiver (unsupervised)": "Leisure Skate: Child with Caregiver (Unsupervised)",
    "Open Space": "Open Space",
    "Open space": "Open Space",
    "Leisure Swim (Men)": "Leisure Swim (Men)",
    "Leisure Swim (Male)": "Leisure Swim (Men)",
}
