from __future__ import annotations

REGISTERED_CATEGORY_TO_TITLES = {
    "Accessibility & Inclusive Programs": [
        "Adapted Active8",
        "Adapted Aquatic Games and Skills",
        "Adapted Arts",
        "Adapted Basketball",
        "Adapted Boccia",
        "Adapted Cooking",
        "Adapted Cooking and Social",
        "Adapted Dance",
        "Adapted Fitness",
        "Adapted Making Music",
        "Adapted Multi-Sport",
        "Adapted Ready, Set, PLAY!",
        "Adapted Recreation",
        "Adapted Sensory Discovery",
        "Adapted Social",
        "Adapted Social Night: Pop Can Club",
        "Adapted Ultra Swim - Advanced",
        "Adapted Ultra Swim - Beginner",
        "Adapted Ultra Swim - Intermediate",
        "Adapted Yoga",
        "Adapted Young Artist",
        "Toronto East York Inclusive Request",
        "Virtual Adapted Active8",
        "Virtual Adapted Arts and Crafts",
        "Virtual Adapted Games: Bingo",
        "Virtual Adapted Games: Board Games",
        "Virtual Adapted Science",
        "Workshop: Sensory Play",
    ],
    "Arts & Crafts": [
        "Art Club",
        "Cartooning",
        "Cartooning: Anime and Manga",
        "Ceramics",
        "Computers: Smartphones",
        "Computers: Smartphones - Intermediate",
        "Computers: Smartphones and Tablets",
        "Computers: Smartphones and Tablets - Intermediate",
        "Crafts",
        "Crafts: Diamond Dots",
        "Crafty Creations",
        "Creative Writing",
        "Crochet",
        "Crochet: Advanced",
        "Design a Space",
        "Drawing",
        "Drawing (Women)",
        "Drawing and Painting",
        "Drawing: Portrait",
        "Embroidery",
        "Felting",
        "Henna",
        "Jewellery Making",
        "Knit, Knots and Loops",
        "Knitting",
        "Make-Up - Advanced (2SLGBTQ+)",
        "Make-Up - Beginner (2SLGBTQ+)",
        "Make-Up - Intermediate (2SLGBTQ+)",
        "Media Arts",
        "Mixed Media",
        "Multi-Arts",
        "Open Studio",
        "Painting",
        "Painting: Acrylic",
        "Painting: Acrylic - Abstract",
        "Painting: Mixed Media",
        "Painting: Mixed Media (2SLGBTQ+)",
        "Painting: Oil",
        "Painting: Watercolour (Women)",
        "Photography",
        "Print Making",
        "Puppet Playhouse",
        "Scrapbooking",
        "Sculpture",
        "Sculpture: Clay",
        "Sewing",
        "Sewing (2SLGBTQ+)",
        "Sewing (Women)",
        "Sewing: Alterations, Repairs, and Upcycling,",
        "Skills and Drills Basics for New Participants",
        "Stained Glass",
        "Stitching",
        "The Art of Leadership",
        "Urban Arts",
        "Wood Burning",
        "Wood Carving",
        "Wood Working",
        "Workshop: 2-Day Clay Creations",
        "Workshop: Fall Paint Night",
        "Workshop: Halloween Slime and Trick or Treat Bags",
        "Workshop: Holiday Paint Night",
        "Workshop: Jewellery Making",
        "Workshop: Paint Acrylic",
        "Workshop: Paint Night",
        "Workshop: Painted Trinket Dishes",
        "Workshop: Painted Wooden Signs",
        "Workshop: Painting Pumpkins",
        "Workshop: Pumpkin Painting",
        "Workshop: Sculpting",
        "Workshop: Tempura Painting - Colour Theory",
        "Workshop: Tempura Painting - Shape & Shading",
        "Workshop: Tempura Painting - Value & Composition",
        "Young Artist",
    ],
    "Camps & School Break Programs": [
        "CampTO",
        "CampTO Explore",
        "CampTO Plus: Arts and Nature",
        "CampTO Plus: Basketball",
        "CampTO Plus: Cooking",
        "CampTO Plus: Dance Basics",
        "CampTO Plus: Drawing and Sketching",
        "CampTO Plus: Gymnastics",
        "CampTO Plus: Skate",
        "CampTO Plus: Soccer",
        "CampTO Plus: Sports",
        "CampTO Plus: Swim Ultra",
        "CampTO Plus: Tennis",
        "CampTO: Early Child",
        "HIIT: Boot Camp",
        "Outdoor HIIT: Boot Camp",
    ],
    "Dance & Movement": [
        "Dance: Acro",
        "Dance: Acro with Showcase",
        "Dance: Argentine Tango",
        "Dance: Basics",
        "Dance: Belly Dance",
        "Dance: Belly Dance (Women)",
        "Dance: Bhangra",
        "Dance: Bollywood",
        "Dance: Breakdance",
        "Dance: Caribbean",
        "Dance: Caribbean (2SLGBTQ+)",
        "Dance: Chinese",
        "Dance: Clogging Beginner",
        "Dance: Clogging Int",
        "Dance: Club Latin",
        "Dance: Contemporary",
        "Dance: Creative Movement",
        "Dance: Fusion",
        "Dance: Hawaiian",
        "Dance: Hip Hop",
        "Dance: Hip Hop (Boys)",
        "Dance: Hip Hop (Girls)",
        "Dance: Hip Hop with Showcase",
        "Dance: Irish",
        "Dance: Jazz",
        "Dance: Jazz Funk (2SLGBTQ+)",
        "Dance: Jazz with Showcase",
        "Dance: K-Pop",
        "Dance: Kuthu",
        "Dance: Latin",
        "Dance: Latin - Advanced",
        "Dance: Line Dance",
        "Dance: Line Dance - Advanced",
        "Dance: Lyrical",
        "Dance: Middle Eastern",
        "Dance: Modern",
        "Dance: Salsa",
        "Dance: Soca",
        "Dance: Social",
        "Dance: Tap",
        "Dance: Tap - Advanced",
        "Dance: Tap Beginner",
        "Dance: Tap Intermediate",
        "Dance: Urban",
    ],
    "Early Childhood & Family Programs": [
        "After-School Program",
        "After-School Recreation Care (ARC)",
        "Badminton: Recreational with Family",
        "Ball Hockey: Instructional with Caregiver",
        "Basketball: Instructional with Caregiver",
        "Community Leadership After-School Program (CLASP)",
        "Cooking with Caregiver",
        "Cooking: Baking with Caregiver",
        "Cooking: Creative Chefs with Caregiver",
        "Cooking: Vegetarian with Caregiver",
        "Crafty Creations with Caregiver",
        "Dance: Ballet with Caregiver",
        "Dance: Basics with Caregiver",
        "Dance: Bollywood With Caregiver",
        "Dance: Creative Movement with Caregiver",
        "Dance: Fusion with Caregiver",
        "Dance: Hip Hop with Caregiver",
        "Dance: Jazz with Caregiver",
        "Dance: K-Pop with Caregiver",
        "Fitness with Family",
        "Garden and Nature with Caregiver",
        "Gardening with Caregiver",
        "Gymnastics with Caregiver",
        "Learn to Skate with Caregiver",
        "Making Music with Caregiver",
        "Martial Arts - Beginner with Caregiver",
        "Multi-Sport: Instructional with Caregiver",
        "Music: Keyboard with Caregiver",
        "Nature with Caregiver",
        "Nature: Little Farmers with Caregiver",
        "Outdoor Stroller Fit",
        "Painting with Caregiver",
        "Painting with Caregiver (2SLGBTQ+)",
        "Painting: Acrylic with Family",
        "Performing Arts with Caregiver",
        "Pickleball: Recreational with Family",
        "Pilates with Baby",
        "Pottery with Caregiver",
        "Pottery: Sculpture with Caregiver",
        "Preschool Swim 1: Penguin",
        "Preschool Swim 1: Penguin (Boys)",
        "Preschool Swim 1: Penguin (Girls)",
        "Preschool Swim 2: Stingray",
        "Preschool Swim 2: Stingray (Girls)",
        "Preschool Swim 3: Otter",
        "Preschool Swim 4: Dolphin",
        "Puppet Playhouse with Caregiver",
        "Ready, Set, PLAY!",
        "Ready, Set, PLAY! with Caregiver",
        "Recreation Adventures with Caregiver",
        "Recreation Discovery with Caregiver",
        "Recreation Discovery with Caregiver (Women)",
        "Recreation Fun and Play with Caregiver",
        "Science: Building Adventures with Caregiver",
        "Science: Scientific Adventures with Caregiver",
        "Science: Scientific Discovery with Caregiver",
        "Sculpture with Caregiver",
        "Sculpture: Clay with Caregiver",
        "Soccer: Instructional with Caregiver",
        "Soccer: Recreational with Caregiver",
        "Stroller Fit",
        "Tennis: Instructional with Caregiver",
        "Tiny Tots Swim",
        "Tiny Tots Swim (Girls)",
        "Wood Working with Caregiver",
        "Workshop: Beaded Snowflakes with Caregiver",
        "Workshop: Cardboard 3D Snowflakes with Caregiver",
        "Workshop: Cardboard Gingerbread House with Caregiver",
        "Workshop: Coding with Robots with Caregiver",
        "Workshop: Craft with Caregiver",
        "Workshop: Diwali crafts with Caregiver",
        "Workshop: Hair (Caregiver and Tot)",
        "Workshop: Halloween crafts with Caregiver",
        "Workshop: Holiday Cards with Caregiver",
        "Workshop: No Sew Halloween Decor with Caregiver",
        "Workshop: Paint Night with Family",
        "Workshop: Painting with Caregiver",
        "Workshop: Popsicle Stick Gingerbread House with Caregiver",
        "Workshop: Popsicle Stick Haunted House with Caregiver",
        "Workshop: Pumpkin Painting with Caregiver",
        "Workshop: Sensory Play with Caregiver",
        "Workshop: Spooky Crafts and Games with Caregiver",
        "Workshop: Young Inventors with Caregiver",
        "Yoga with Baby",
        "Yoga with Caregiver",
        "Yoga with Family",
        "Young Artist with Caregiver",
        "Zumba with Family",
    ],
    "Education & Life Skills": [
        "25 x 2 Tips for your Toolbox",
        "Basic First Aid CPR-C & AED",
        "Club: Homework",
        "Coding",
        "Computers",
        "Computers: Laptop",
        "Computers: Laptop - Intermediate",
        "Computers: Tablet",
        "Computers: Video Game Design",
        "Computers: Web Design",
        "Cooking",
        "Cooking: Baking",
        "Cooking: Baking (2SLGBTQ+)",
        "Cooking: Baking (Women)",
        "Cooking: Cake Decorating",
        "Cooking: Cake Decorating - Advanced",
        "Cooking: Creative Chefs",
        "Cooking: Cultural",
        "Cooking: Cultural (2SLGBTQ+)",
        "Cooking: Skills",
        "Cooking: Skills (Women)",
        "Cooking: Vegetarian",
        "Gardening",
        "Geography: Geographic Discovery",
        "Hair: Braiding Beginners",
        "Hair: Braiding, Weaving and Wigs",
        "Intermediate First Aid with CPR-C & AED",
        "Intermediate First Aid with CPR-C & AED - Recert",
        "Language: Spanish",
        "Language: Spanish - Advanced",
        "Language: Spanish - Intermediate",
        "Learn to Weight Train - Small Group",
        "Nature",
        "Nutrition Program",
        "Pool Operator Level 1",
        "Pool Operator Level 2",
        "Recreation Adventures",
        "Recreation Discovery",
        "Science",
        "Science (Girls)",
        "Science of Sports",
        "Science: Building Adventures",
        "Science: Building Discovery",
        "Science: Scientific Adventures",
        "Science: Scientific Discovery",
        "Tae Kwon Do Learn to Move",
        "Workshop Holiday Baking",
        "Workshop: Baking",
        "Workshop: Bath soap",
        "Workshop: Beaded Crystal Fairies",
        "Workshop: Beaded Snowflakes",
        "Workshop: Beaded Spiders",
        "Workshop: Beeswax Rolled Candles",
        "Workshop: Breakfast with Santa",
        "Workshop: Candle Making",
        "Workshop: Cardboard 3D Snowflakes",
        "Workshop: Cardboard Gingerbread House",
        "Workshop: Coding with Robots",
        "Workshop: Coding with Robots - Intermediate",
        "Workshop: Computer-Laptop",
        "Workshop: Cricut",
        "Workshop: Diwali crafts",
        "Workshop: Fall Baking",
        "Workshop: Fall Candle Making",
        "Workshop: Fall Candle Making w/Pressed Flowers",
        "Workshop: Fall Harvest",
        "Workshop: Fall Paper Lanterns",
        "Workshop: Family Holiday Jewellery Making",
        "Workshop: Felt Poinsettia Wreath",
        "Workshop: Festive Tree Tapestry Weaving",
        "Workshop: Fraud Prevention for Older Adults",
        "Workshop: Halloween Craft",
        "Workshop: Halloween Crafts",
        "Workshop: Halloween Crafts & Games",
        "Workshop: Holiday Candle Making",
        "Workshop: Holiday Cards",
        "Workshop: Holiday Craft",
        "Workshop: Holiday Crafts",
        "Workshop: Holiday Crafts and Baking",
        "Workshop: Holiday Crochet",
        "Workshop: Holiday Felting",
        "Workshop: Holiday Gift Making",
        "Workshop: Jewelry Making",
        "Workshop: Knitting",
        "Workshop: Line Dance Cafe Social",
        "Workshop: Linoleum Block Printing",
        "Workshop: Melt and Pour Soap Making",
        "Workshop: Melting Beads",
        "Workshop: Natural Dyeing - Eco Printing",
        "Workshop: Popsicle Stick Gingerbread House",
        "Workshop: Present Making",
        "Workshop: Rolled Beeswax Candles",
        "Workshop: STEM",
        "Workshop: Sea Glass Art",
        "Workshop: Sew a Bag",
        "Workshop: Sun Dyeing",
        "Workshop: Tree of Life Pendant",
        "Workshop: Volunteer Information Session",
        "Workshop: Weaving",
        "Workshop: Wreath Making",
        "Workshop: Young Inventors",
        "Young Women's Program",
        "Youth Council",
        "Youth Leadership Program",
    ],
    "Fitness & Wellness": [
        "Awesome Abdominal Training",
        "Cardio Combinations",
        "Cardio Dance",
        "Cardio Dance: Afro and Soca Fusion",
        "Cardio Dance: Bollywood",
        "Cardio: High/Low",
        "Cardio: Rebounder",
        "Club: Explorers Walking and Social",
        "Cycle Fit",
        "Deep Dive Muscles",
        "Deep H2O Muscles",
        "Functional Fit",
        "Functional Mobility: TIME",
        "Gentle Fit",
        "Gentle Fit (Women)",
        "Meditation",
        "Mobility and Strength: Chair",
        "Muscle Up Class",
        "Osteo Fit",
        "Outdoor Gentle Fit",
        "Outdoor Tai Chi",
        "Outdoor Tai Chi - Intermediate",
        "Outdoor Walk Fit",
        "Outdoor Yoga",
        "Pedal and Strength",
        "Pilates",
        "Pilates (Women)",
        "Pilates with weights",
        "Pilates: Chair",
        "Qigong",
        "Step",
        "Strength and Conditioning",
        "Tai Chi",
        "Tai Chi - Advanced",
        "Walk Fit",
        "Walking with Purpose",
        "Yoga",
        "Yoga (Women)",
        "Yoga/Pilates Fusion",
        "Yoga: Chair",
        "Zumba Gold®",
        "Zumba®",
        "Zumba® (Women)",
        "Zumba® Toning",
    ],
    "Music & Performing Arts": [
        "Drama",
        "Drop the Mic Music",
        "Improv",
        "Making Music",
        "Music: Cello - Private",
        "Music: Drumming - African",
        "Music: Drumming - Private",
        "Music: Drumming - Steel Pan",
        "Music: Guitar",
        "Music: Guitar - Advanced",
        "Music: Guitar - Private",
        "Music: Guitar - Tri Private",
        "Music: Keyboard",
        "Music: Keyboard - Advanced",
        "Music: Keyboard - Private",
        "Music: Keyboarding",
        "Music: Piano",
        "Music: Piano - Advanced",
        "Music: Piano - Private",
        "Music: Singing",
        "Music: Singing - Private",
        "Music: Ukulele - Private",
        "Music: Violin - Private",
        "Musical Theatre",
        "Stroke Improvement",
        "Stroke Improvement - Small Group",
    ],
    "Skating & Ice Programs": [
        "Figure Skating",
        "Goalie Skills",
        "Hockey Skills",
        "Hockey Skills (Women)",
        "Home Ice Hockey",
        "Home Ice Hockey (Girls)",
        "Learn To Skate (Women)",
        "Learn To Skate - Advanced",
        "Learn To Skate - Beginner - Small Group",
        "Learn to Skate - Beginner",
        "Learn to Skate 1",
        "Learn to Skate 2",
        "Learn to Skate 3",
        "Learn to Skate 4",
        "Learn to Skate 5",
        "Learn to Skate: Older Adult",
        "Power Skating - Beginner",
        "Shinny: Older Adult",
        "Shinny: Older Adult (Women)",
        "Skateboarding: Instructional",
    ],
    "Social, Games & Community Programs": [
        "Cards: Bridge Progressive",
        "Cards: Cribbage",
        "Club (Girls)",
        "Club: Chess",
        "Club: Dungeons and Dragons",
        "Club: Reading",
        "Club: Social",
        "Games",
        "Games, Partners and Teamwork",
        "Games: Billiards (Women)",
        "Games: Board",
        "Games: Chess",
        "Games: Dominoes",
        "Games: Dungeons & Dragons",
        "Games: Dungeons & Dragons (Women)",
    ],
    "Special Event": [
        "Special Event: Breakfast with Santa",
        "Special Event: Breakfast with Santa (with Caregiver)",
        "Special Event: Halloween Night",
        "Special Event: Halloween Party with Caregiver",
        "Special Event: Holiday",
        "Special Event: Holiday Cards & Ornaments",
        "Special Event: Holiday Night",
        "Special Event: Holiday Party with Caregiver",
        "Special Event: Holiday Workshop",
        "Special Event: Holiday Workshop with Caregiver",
        "Special Event: Santa's Workshop with Caregiver",
        "Special Event: Spooktober",
    ],
    "Sports & Martial Arts": [
        "Advanced Kickboxing",
        "Aikido - Advanced",
        "Aikido - Beginner",
        "Arnis/Kali - Advanced",
        "Arnis/Kali - Beginner",
        "Badminton",
        "Badminton: Instructional",
        "Badminton: Recreational",
        "Badminton: Recreational Tournament",
        "Ball Hockey: Instructional",
        "Ball Hockey: Recreational",
        "Balls and Bells",
        "Baseball: Instructional",
        "Basketball",
        "Basketball: House League",
        "Basketball: Instructional",
        "Basketball: Instructional (Boys)",
        "Basketball: Instructional (Girls)",
        "Basketball: Recreational",
        "Basketball: Recreational (Men)",
        "Basketball: Recreational (Women)",
        "Cardio: Kickboxing",
        "Cheerleading",
        "Clinic: Pickleball",
        "Clinic: Tennis - Hitting Spin Shots",
        "Clinic: Tennis - Reading Plays & Ball Direction",
        "Clinic: Tennis - Serving & Returning Serves",
        "Cricket",
        "Cricket: Instructional",
        "Cycling Tour de France",
        "Dance: Ballet",
        "Dance: Ballet with Showcase",
        "Dance: Ballroom",
        "Dance: Ballroom - Advanced",
        "Dance: Ballroom Latin",
        "Dodgeball: Instructional",
        "Dodgeball: Recreational",
        "First Tee Golf",
        "Flag Football: Instructional",
        "Golf - Private",
        "Golf: Instructional",
        "Golf: Recreational",
        "Gymnastics",
        "Gymnastics - Advanced",
        "Gymnastics - Beginner",
        "Gymnastics - Intermediate",
        "Gymnastics: Competitive with Showcase",
        "Gymnastics: Tumbling",
        "Gymnastics: Tumbling - Beginner",
        "Gymnastics: Tumbling - Intermediate",
        "HDA Ball Hockey",
        "HDA Ball Hockey - Referral",
        "HIIT: Balance Ball",
        "Hapkido - Advanced",
        "Hapkido - Beginner",
        "Intro to Kickboxing",
        "Karate - Advanced",
        "Karate - Beginner",
        "Lacrosse: Instructional",
        "Martial Arts - Advanced",
        "Martial Arts - Beginner",
        "Multi-Sport",
        "Multi-Sport: Instructional",
        "Multi-Sport: Instructional (Girls)",
        "Multi-Sport: Recreational",
        "Noodle Gym",
        "Philpott Tennis",
        "Pickleball",
        "Pickleball: Instructional",
        "Pickleball: Recreational",
        "Pickleball: Recreational Tournament",
        "Rhythmic Gymnastics",
        "Self Defence (Women)",
        "Self Defence - Advanced",
        "Self Defence - Beginner",
        "Soccer: House League",
        "Soccer: Instructional",
        "Soccer: Recreational",
        "Table Tennis",
        "Table Tennis: Instructional",
        "Table Tennis: Recreational",
        "Tae Kwon Do - Advanced",
        "Tae Kwon Do - Beginner",
        "Tae Kwon Do - Beginner (Girls)",
        "Tae Kwon Do with Belts",
        "Tennis - Private",
        "Tennis - Semi Private",
        "Tennis - Small Group",
        "Tennis: Instructional",
        "Tennis: Instructional - Advanced",
        "Tennis: Instructional - Advanced - Small Group",
        "Tennis: Instructional - Beginner",
        "Tennis: Instructional - Intermediate",
        "Tennis: Instructional - Intermediate - Small Group",
        "Tennis: Recreational",
        "Toronto Women's Softball: House League B Division",
        "Toronto Women's Softball: House League Ball Busters",
        "Toronto Women's Softball: House League Cherry Bombs",
        "Toronto Women's Softball: House League Hustlers",
        "Toronto Women's Softball: House League Kstangs",
        "Toronto Women's Softball: House League Wild Pitches",
        "Toronto Women's Softball: House League Wreckers",
        "Volleyball: Instructional",
        "Volleyball: Instructional (Girls)",
        "Volleyball: Recreational",
        "Workshop: Baseball",
        "Workshop: Soccer",
    ],
    "Swimming & Aquatics": [
        "Adult Swim 1",
        "Adult Swim 1 (Women)",
        "Adult Swim 1 - Small Group",
        "Adult Swim 2",
        "Adult Swim 2 (Women)",
        "Adult Swim 2 - Small Group",
        "Adult Swim 3",
        "Adult Swim 3 (Women)",
        "Adult Swim 3 - Small Group",
        "Aquatic Fitness Conference and Instructor Certification",
        "Aquatic Fitness Conference and Instructor Recertification",
        "Aquatic Fitness Instructor Certification",
        "Aquatic Fitness Instructor: Specialty - Mind and Body",
        "Bronze Cross",
        "Bronze Cross & Intermediate First Aid with CPR-C & AED",
        "Bronze Cross (Girls)",
        "Bronze Cross Challenge Exam",
        "Bronze Cross Recert",
        "Bronze Medallion",
        "Bronze Medallion & Basic First Aid CPR C & AED",
        "Bronze Medallion, Bronze Cross & Intermediate First Aid with",
        "Bronze Star",
        "Bronze Star and Basic First Aid (CPR A)",
        "Challenge Swim: Bronze",
        "Challenge Swim: Gold",
        "Challenge Swim: Silver",
        "Circuit Training",
        "Creative Cueing",
        "Equipment Overload Circuits",
        "Future Lifeguards",
        "Guardian Swim 1",
        "Guardian Swim 1 (Boys)",
        "Guardian Swim 1 (Girls)",
        "Guardian Swim 2",
        "Guardian Swim 2 (Girls)",
        "Guardian Swim 3",
        "H2O Flow",
        "High Intensity Interval Training",
        "Indigenous Lens Swim Lessons",
        "Instructor Recert Course",
        "Jump, Punch, Kick and Jab!",
        "Kick up your Combo's",
        "Kickboxing/TaeKwon Aqua Theory",
        "Mentorship with Moxy 2",
        "Mentorship with Moxy!",
        "National Lifeguard - Pool",
        "National Lifeguard - Pool Recert",
        "National Lifeguard - Waterfront Core",
        "National Lifeguard - Waterfront Recert",
        "Older Adult Swim 1",
        "Painting: Watercolour",
        "Painting: Watercolour - Advanced",
        "Pedagogical Practice",
        "Pottery",
        "Pottery: Sculpture",
        "Pottery: Wheel",
        "Ranger Patrol",
        "Rookie Patrol",
        "Rookie/Ranger/Star Patrol Combined",
        "SPLASH Swim Team",
        "Splash Team Class",
        "Splash Team Class – Winter Olympics",
        "Sports Training the Watergym of the Future",
        "Star Patrol",
        "Swim Fit",
        "Swim Fit (Women)",
        "Swim Lessons - Private",
        "Swim Lessons - Private (Girls)",
        "Swim and Lifesaving Instructor",
        "Swim to Survive",
        "Ultra Swim 1",
        "Ultra Swim 1 (Boys)",
        "Ultra Swim 1 (Girls)",
        "Ultra Swim 1 - Small Group",
        "Ultra Swim 1 - Small Group (Girls)",
        "Ultra Swim 2",
        "Ultra Swim 2 (Boys)",
        "Ultra Swim 2 (Girls)",
        "Ultra Swim 2 - Small Group",
        "Ultra Swim 2 - Small Group (Girls)",
        "Ultra Swim 3",
        "Ultra Swim 3 (Boys)",
        "Ultra Swim 3 (Girls)",
        "Ultra Swim 3 - Semi Private",
        "Ultra Swim 3 - Small Group",
        "Ultra Swim 3 - Small Group (Girls)",
        "Ultra Swim 4",
        "Ultra Swim 4 (Boys)",
        "Ultra Swim 4 (Girls)",
        "Ultra Swim 4 - Small Group",
        "Ultra Swim 4 - Small Group (Girls)",
        "Ultra Swim 5",
        "Ultra Swim 5 (Boys)",
        "Ultra Swim 5 (Girls)",
        "Ultra Swim 5 - Semi Private",
        "Ultra Swim 5 - Small Group",
        "Ultra Swim 5 - Small Group (Girls)",
        "Ultra Swim 6",
        "Ultra Swim 6 (Girls)",
        "Ultra Swim 6 - Small Group",
        "Ultra Swim 7",
        "Ultra Swim 7 (Boys)",
        "Ultra Swim 7 (Girls)",
        "Ultra Swim 7 - Small Group",
        "Ultra Swim 8",
        "Ultra Swim 8 (Girls)",
        "Ultra Swim 8 - Small Group",
        "Ultra Swim 9",
        "Ultra Swim 9 (Girls)",
        "Ultra Swim 9 - Small Group",
        "Ultra Youth Swim 1",
        "Ultra Youth Swim 1 (Girls)",
        "Ultra Youth Swim 2",
        "Ultra Youth Swim 2 (Girls)",
        "Ultra Youth Swim 3",
        "WaterArt Acronym",
    ],
}

RAW_TO_CANONICAL_REGISTERED_ACTIVITY = {
    "Coding": "Coding",
    "Coding:": "Coding",
    "Dance: Ballet With Caregiver": "Dance: Ballet with Caregiver",
    "Dance: Ballet with Caregiver": "Dance: Ballet with Caregiver",
    "Dance: Basics With Caregiver": "Dance: Basics with Caregiver",
    "Dance: Basics with Caregiver": "Dance: Basics with Caregiver",
    "Dance: Creative Movement With Caregiver": "Dance: Creative Movement with Caregiver",
    "Dance: Creative Movement with Caregiver": "Dance: Creative Movement with Caregiver",
    "Dance: Creative Movement with caregiver": "Dance: Creative Movement with Caregiver",
    "Dance: Hip Hop": "Dance: Hip Hop",
    "Dance: Hip-Hop": "Dance: Hip Hop",
    "Dance: Hip Hop With Caregiver": "Dance: Hip Hop with Caregiver",
    "Dance: Hip Hop with Caregiver": "Dance: Hip Hop with Caregiver",
    "Learn To Skate - Beginner": "Learn to Skate - Beginner",
    "Learn to Skate - Beginner": "Learn to Skate - Beginner",
    "Learn To Skate with Caregiver": "Learn to Skate with Caregiver",
    "Learn to Skate with Caregiver": "Learn to Skate with Caregiver",
    "Learn To Weight Train - Small Group": "Learn to Weight Train - Small Group",
    "Learn to Weight Train - Small Group": "Learn to Weight Train - Small Group",
    "Martial Arts - Beginner With Caregiver": "Martial Arts - Beginner with Caregiver",
    "Martial Arts - Beginner with Caregiver": "Martial Arts - Beginner with Caregiver",
    "Multi Arts": "Multi-Arts",
    "Multi-Arts": "Multi-Arts",
    "Pilates With Baby": "Pilates with Baby",
    "Pilates with Baby": "Pilates with Baby",
    "Pottery With Caregiver": "Pottery with Caregiver",
    "Pottery with Caregiver": "Pottery with Caregiver",
    "Tae Kwon Do Learn To Move": "Tae Kwon Do Learn to Move",
    "Tae Kwon Do Learn to Move": "Tae Kwon Do Learn to Move",
    "Workshop: Fall Baking": "Workshop: Fall Baking",
    "Workshop:Fall Baking": "Workshop: Fall Baking",
    "Workshop: Halloween Crafts": "Workshop: Halloween Crafts",
    "Workshop: Halloween crafts": "Workshop: Halloween Crafts",
    "Zumba with Family": "Zumba with Family",
    "Zumba® with Family": "Zumba with Family",
    "CampTO Plus: Drawing & Sketching": "CampTO Plus: Drawing and Sketching",
    "CampTO Plus: Drawing and Sketching": "CampTO Plus: Drawing and Sketching",
    "Family wtih Fitness": "Fitness with Family",
    "Fitness with Family": "Fitness with Family",
    "Zumba® (Women)": "Zumba® (Women)",
    "Zumba (Women)": "Zumba® (Women)",
    "Zumba®": "Zumba®",
    "Zumba": "Zumba®",
    "Zumba Gold®": "Zumba Gold®",
    "Zumba® Gold": "Zumba Gold®",
}

REGISTERED_TITLE_TO_CATEGORY = {
    title: category
    for category, titles in REGISTERED_CATEGORY_TO_TITLES.items()
    for title in titles
}

OTHER_REGISTERED_CATEGORY = "Other Programs"
