from __future__ import annotations

REGISTERED_CATEGORY_TO_TITLES = {
    "Accessibility & Inclusive Programs": [
        "Adapted Active8",
        "Adapted Aquatic Games and Skills",
        "Adapted Arts",
        "Adapted Basketball",
        "Adapted Boccia",
        "Adapted CampTO Explore",
        "Adapted CampTO Explore: Iron Butterflies",
        "Adapted Cooking",
        "Adapted Cooking and Social",
        "Adapted Counsellor in Training",
        "Adapted Dance",
        "Adapted Fitness",
        "Adapted Making Music",
        "Adapted Multi-Sport",
        "Adapted Ready, Set, PLAY!",
        "Adapted Recreation",
        "Adapted Sensory Discovery",
        "Adapted Social",
        "Adapted Social Night: Pop Can Club",
        "Adapted Ultra Swim - Advanced",
        "Adapted Ultra Swim - Beginner",
        "Adapted Ultra Swim - Intermediate",
        "Adapted Yoga",
        "Adapted Young Artist",
        "Scarborough Inclusive Request",
        "Sensory Discovery with Caregiver",
        "Toronto East York Inclusive Request",
        "Virtual Adapted Active8",
        "Virtual Adapted Arts and Crafts",
        "Virtual Adapted CampTO",
        "Virtual Adapted Games: Bingo",
        "Virtual Adapted Games: Board Games",
        "Virtual Adapted Science",
        "Workshop: Sensory Discovery",
        "Workshop: Sensory Discovery with Caregiver",
        "Workshop: Sensory Play",
    ],
    "Arts & Crafts": [
        "Animation",
        "Art Club",
        "Cartooning",
        "Cartooning: Anime and Manga",
        "Ceramics",
        "Computers: Smartphones",
        "Computers: Smartphones and Tablets",
        "Crafts",
        "Crafts: Diamond Dots",
        "Crafty Creations",
        "Create Your Space",
        "Creative Writing",
        "Creative Writing Comic Books/Anime",
        "Crochet",
        "Crochet: Advanced",
        "Drawing",
        "Drawing and Painting",
        "Drawing and Painting: Landscape",
        "Drawing: Portrait",
        "Embroidery",
        "Felting",
        "Henna",
        "Jewellery Making",
        "Knitting",
        "Make-Up - Advanced (2SLGBTQ+)",
        "Make-Up - Beginner (2SLGBTQ+)",
        "Make-Up - Beginner (2SLGBTQ+) - Pilot",
        "Make-Up - Intermediate (2SLGBTQ+)",
        "Make-Up - Intermediate (2SLGBTQ+) - Pilot",
        "Media Arts",
        "Mixed Media",
        "Multi Arts",
        "Open Studio",
        "Painting",
        "Painting: Acrylic",
        "Painting: Acrylic - Abstract",
        "Painting: Mixed Media",
        "Painting: Mixed Media (2SLGBTQ+)",
        "Painting: Oil",
        "Photography",
        "Print Making",
        "Puppet Playhouse",
        "Scrapbooking",
        "Sculpture",
        "Sculpture: Clay",
        "Sewing",
        "Sewing (2SLGBTQ+)",
        "Sewing (Women)",
        "Skills and Drills Basics for New Participants",
        "Stained Glass",
        "Steel Pan",
        "The Art of Leadership",
        "Wood Burning",
        "Wood Carving",
        "Wood Working",
        "Workshop Character drawing: Ash Ketchum",
        "Workshop Character drawing: Sailor Moon",
        "Workshop Series: Crochet",
        "Workshop: 2-Day Clay Creations",
        "Workshop: Crafty Creations",
        "Workshop: Decoupage Canvas Art Mixed Media",
        "Workshop: Drawing - Shape and Shading",
        "Workshop: Father's Day Crafts",
        "Workshop: Jewellery Making",
        "Workshop: Paint Acrylic",
        "Workshop: Paint Night",
        "Workshop: Paint Night Acrylic",
        "Workshop: Paint Night Oil Pastels",
        "Workshop: Rock Painting",
        "Workshop: Sculpting",
        "Workshop: Song Circle with Craft",
        "Workshop: Summer Ceramic",
        "Workshop: Summer Vacation Destination Painting",
        "Young Artist",
    ],
    "Camps & School Break Programs": [
        "CampTO",
        "CampTO Explore",
        "CampTO Plus Museums: Cooking Camp At Montgomery’s Inn",
        "CampTO Plus Museums: Creative Arts at Montgomery's Inn",
        "CampTO Plus: Arts and Nature",
        "CampTO Plus: Ball Hockey",
        "CampTO Plus: Baseball",
        "CampTO Plus: Basketball",
        "CampTO Plus: Cheerleading",
        "CampTO Plus: Circus",
        "CampTO Plus: Computers",
        "CampTO Plus: Cooking",
        "CampTO Plus: Crafts",
        "CampTO Plus: Creative Writing",
        "CampTO Plus: Cycling - Advanced (On the Road)",
        "CampTO Plus: Cycling - Beginner",
        "CampTO Plus: Cycling - Intermediate (Bike Handling Skills)",
        "CampTO Plus: Dance Basics",
        "CampTO Plus: Dance: Acro",
        "CampTO Plus: Dance: Hip Hop",
        "CampTO Plus: Drama",
        "CampTO Plus: Drawing and Sketching",
        "CampTO Plus: Environmental Adventure",
        "CampTO Plus: Flag Football",
        "CampTO Plus: French",
        "CampTO Plus: Golf",
        "CampTO Plus: Gymnastics",
        "CampTO Plus: Island Ecologist",
        "CampTO Plus: Island Explorer",
        "CampTO Plus: Island Voyager",
        "CampTO Plus: Magic",
        "CampTO Plus: Multi Arts",
        "CampTO Plus: Music",
        "CampTO Plus: Musical Theatre",
        "CampTO Plus: Photography",
        "CampTO Plus: Racquet and Paddle",
        "CampTO Plus: Science",
        "CampTO Plus: Skateboarding",
        "CampTO Plus: Soccer",
        "CampTO Plus: Sports",
        "CampTO Plus: Sports (Girls)",
        "CampTO Plus: Swim Ultra",
        "CampTO Plus: Tennis",
        "CampTO Plus: Track and Field",
        "CampTO Plus: Visual Arts",
        "CampTO Plus: Volleyball",
        "CampTO Plus: Volleyball (Girls)",
        "Counsellor in Training",
        "Dance: Ballet with Recital",
        "Dance: Hip Hop with Recital",
        "Dance: Tap with Recital",
        "HIIT: Boot Camp",
        "Olympium Camp Swim",
        "Outdoor HIIT: Boot Camp",
    ],
    "Dance & Movement": [
        "Dance: Acro",
        "Dance: Acro with Showcase",
        "Dance: Argentine Tango",
        "Dance: Basics",
        "Dance: Belly Dance",
        "Dance: Belly Dance (Women)",
        "Dance: Bhangra",
        "Dance: Bollywood",
        "Dance: Breakdance",
        "Dance: Caribbean",
        "Dance: Chinese",
        "Dance: Clogging",
        "Dance: Club Latin",
        "Dance: Contemporary",
        "Dance: Creative Movement",
        "Dance: Fusion",
        "Dance: Hawaiian",
        "Dance: Hip Hop",
        "Dance: Hip Hop (Boys)",
        "Dance: Hip Hop with Showcase",
        "Dance: Hip-hop",
        "Dance: Jazz",
        "Dance: K-Pop",
        "Dance: Latin",
        "Dance: Latin - Advanced",
        "Dance: Line Dance",
        "Dance: Line Dance - Advanced",
        "Dance: Line Dance - Intermediate",
        "Dance: Lyrical",
        "Dance: Middle Eastern",
        "Dance: Modern",
        "Dance: Salsa",
        "Dance: Soca",
        "Dance: Social",
        "Dance: Tap",
        "Dance: Tap - Advanced",
        "Workshop: Dance",
        "Workshop: Dance - HipHop",
    ],
    "Early Childhood & Family Programs": [
        "After-School Program",
        "After-School Recreation Care (ARC)",
        "Badminton: Recreational with Family",
        "Ball Hockey: Instructional with Caregiver",
        "Baseball: Instructional with Caregiver",
        "Basketball: Instructional with Caregiver",
        "Coding: Robots with Caregiver",
        "Community Leadership After-School Program (CLASP)",
        "Cooking with Caregiver",
        "Cooking: Baking with Caregiver",
        "Cooking: Creative Chefs with Caregiver",
        "Crafty Creations with Caregiver",
        "Cycling: Instructional - Beginner with Caregiver",
        "Dance: Acro with Caregiver",
        "Dance: Ballet With Caregiver",
        "Dance: Ballet with Caregiver",
        "Dance: Basics with Caregiver",
        "Dance: Bollywood With Caregiver",
        "Dance: Creative Movement With Caregiver",
        "Dance: Creative Movement with Caregiver",
        "Dance: Creative Movement with caregiver",
        "Dance: Fusion with Caregiver",
        "Dance: Hip Hop With Caregiver",
        "Dance: Hip Hop with Caregiver",
        "Dance: Jazz with Caregiver",
        "Dance: K-Pop with Caregiver",
        "Family Fitness",
        "Fitness with Family",
        "Garden and Nature with Caregiver",
        "Gardening with Caregiver",
        "Gymnastics with Caregiver",
        "Learn To Skate with Caregiver",
        "Making Music with Caregiver",
        "Martial Arts - Beginner with Caregiver",
        "Multi-Sport: Instructional with Caregiver",
        "Music: Keyboard with Caregiver",
        "Nature with Caregiver",
        "Nature: Little Farmers with Caregiver",
        "Outdoor Stroller Fit",
        "Outdoor Yoga With Caregiver",
        "Outdoor Yoga with Baby",
        "Painting with Caregiver",
        "Painting with Caregiver (2SLGBTQ+)",
        "Painting: Acrylic with Family",
        "Performing Arts with Caregiver",
        "Pickleball: Recreational with Family",
        "Pilates With Baby",
        "Pilates with Baby",
        "Pottery with Caregiver",
        "Pottery: Sculpture with Caregiver",
        "Preschool Swim 1: Penguin",
        "Preschool Swim 1: Penguin (Boys)",
        "Preschool Swim 1: Penguin (Girls)",
        "Preschool Swim 2: Stingray",
        "Preschool Swim 2: Stingray (Girls)",
        "Preschool Swim 3: Otter",
        "Preschool Swim 4: Dolphin",
        "Puppet Playhouse with Caregiver",
        "Ready, Set, PLAY!",
        "Ready, Set, PLAY! with Caregiver",
        "Recreation Adventures with Caregiver",
        "Recreation Discovery with Caregiver",
        "Recreation Fun and Play with Caregiver",
        "Science: Building Adventures with Caregiver",
        "Science: Building Discovery with Caregiver",
        "Science: Scientific Adventures with Caregiver",
        "Science: Scientific Discovery with Caregiver",
        "Sculpture with Caregiver",
        "Soccer: Instructional with Caregiver",
        "Soccer: Recreational with Caregiver",
        "Tennis: Instructional with Caregiver",
        "Tiny Tots Swim",
        "Tiny Tots Swim (Girls)",
        "Workshop: Coding with Robots with Caregiver",
        "Workshop: Dance - Creative Movement with caregiver",
        "Workshop: Dance with Caregiver",
        "Workshop: Father's Day Sculpting with Caregiver",
        "Workshop: Hair (Caregiver and Tot)",
        "Workshop: Making Music with Caregiver",
        "Workshop: Making music with Caregiver",
        "Workshop: Making music with caregiver",
        "Workshop: Motor & Pre-Writing Development with Caregiver",
        "Workshop: Paint Night with Family",
        "Workshop: Painted Ice Cream Bowls With Caregiver",
        "Workshop: Story time series with caregiver",
        "Workshop: Summertime Crafts and Games With Caregiver",
        "Workshop: Young Inventors with Caregiver",
        "Yoga With Baby",
        "Yoga with Baby",
        "Yoga with Caregiver",
        "Yoga with Family",
        "Young Artist with Caregiver",
        "Zumba® with Family",
    ],
    "Education & Life Skills": [
        "25 x 2 Tips for your Toolbox",
        "Basic First Aid CPR-C & AED",
        "Club: Homework",
        "Coding with Robots",
        "Computer-Laptop",
        "Computers",
        "Computers: Laptop",
        "Computers: Laptop - Intermediate",
        "Computers: Tablet",
        "Computers: Video Game Design",
        "Computers: Web Design",
        "Cooking",
        "Cooking : Baking",
        "Cooking: Baking",
        "Cooking: Baking (2SLGBTQ+)",
        "Cooking: Baking (Women)",
        "Cooking: Cake Decorating",
        "Cooking: Cake Decorating - Advanced",
        "Cooking: Creative Chefs",
        "Cooking: Cultural",
        "Cooking: Desserts",
        "Cooking: Skills",
        "Cooking: Skills (Women)",
        "Cooking: Vegetarian",
        "Emergency First Aid (CPR B)",
        "Gardening",
        "Geography: Geographic Discovery",
        "Hair: Braiding, Weaving and Wigs",
        "Intermediate First Aid with CPR-C & AED",
        "Intermediate First Aid with CPR-C & AED - Recert",
        "Language: Spanish",
        "Language: Spanish - Advanced",
        "Language: Spanish - Intermediate",
        "Learn To Weight Train - Small Group",
        "Nature",
        "Nutrition Program",
        "Pool Attend & Intermediate First Aid with CPR-C & AED",
        "Recreation Adventures",
        "Recreation Discovery",
        "Science",
        "Science - STEM",
        "Science: Building Adventures",
        "Science: Building Discovery",
        "Science: Scientific Adventures",
        "Science: Scientific Discovery",
        "Special Event: Cake Decorating Workshop",
        "Standard First Aid (CPR C)",
        "Standard First Aid (CPR C) Recert",
        "Tae Kwon Do Learn To Move",
        "Tae Kwon Do Learn to Move",
        "Workshop Roller Coaster Design",
        "Workshop Science Experiment",
        "Workshop Spaghetti Tower",
        "Workshop: Baking",
        "Workshop: Beaded Butterflies",
        "Workshop: Beaded Crystal Fairies",
        "Workshop: Beaded Plant Pokes",
        "Workshop: Candle Making",
        "Workshop: Coding with Robots",
        "Workshop: Coding with Robots - Intermediate",
        "Workshop: Cricut",
        "Workshop: Cricut Project - Sun Catchers",
        "Workshop: DIY Flower Press",
        "Workshop: Fall Harvest",
        "Workshop: Father's Day Button Making and Cark Making",
        "Workshop: Felt Flower Brooches",
        "Workshop: Hammered Flower Prints",
        "Workshop: Intro to Mini Loom Weaving",
        "Workshop: Mala Necklace",
        "Workshop: Melt and Pour Soap Making",
        "Workshop: Melting Beads",
        "Workshop: Natural Dyeing with Wool",
        "Workshop: Paper Flower Making",
        "Workshop: Paper Making",
        "Workshop: Paper Spring Lantern",
        "Workshop: Quick Pickling",
        "Workshop: STEM",
        "Workshop: Science - Soap-Powered Boat",
        "Workshop: Science - Wind Turbine",
        "Workshop: Spinning",
        "Workshop: Sun Dyeing",
        "Workshop: Volunteer Information Session",
        "Workshop: Weaving",
        "Workshop: Wire Pendant Wrapping",
        "Workshop: Young Inventors",
        "Workshop: Young Inventors - Nature Perspective",
        "Young Women's Program",
        "Youth Council",
        "Youth Leadership Program",
    ],
    "Fitness & Wellness": [
        "Awesome Abdominal Training",
        "Cardio Combinations",
        "Cardio Dance",
        "Cardio Dance: Afro and Soca Fusion",
        "Cardio Dance: Bollywood",
        "Cardio High/Low",
        "Cardio: High/Low",
        "Cardio: Rebounder",
        "Club: Explorers Walking and Social",
        "Cycle Fit",
        "Deep Dive Muscles",
        "Deep H2O Muscles",
        "Functional Fit",
        "Functional Mobility: TIME",
        "Gentle Fit",
        "Gentle Fit (Women)",
        "Meditation",
        "Mobility and Strength: Chair",
        "Muscle Up Class",
        "Osteo Fit",
        "Outdoor Gentle Fit",
        "Outdoor Strength and Conditioning",
        "Outdoor Tai Chi",
        "Outdoor Tai Chi - Intermediate",
        "Outdoor Walk Fit",
        "Outdoor Yoga",
        "Outdoor Yoga/Pilates Fusion",
        "Pedal and Strength",
        "Pilates",
        "Pilates (Women)",
        "Pilates: Chair",
        "Qigong",
        "Step",
        "Strength and Conditioning",
        "Tai Chi",
        "Tai Chi - Advanced",
        "Tai Chi - Intermediate",
        "Walk Fit",
        "Walking with Purpose",
        "Yoga",
        "Yoga (Women)",
        "Yoga-Chair",
        "Yoga/Pilates Fusion",
        "Yoga: Chair",
        "Zumba",
        "Zumba (Women)",
        "Zumba Gold®",
        "Zumba®",
        "Zumba® Gold",
        "Zumba® Toning",
    ],
    "Music & Performing Arts": [
        "Drama",
        "Drop the Mic Music",
        "Improv",
        "Making Music",
        "Music: Cello - Private",
        "Music: Drumming - African",
        "Music: Drumming - Private",
        "Music: Guitar",
        "Music: Guitar - Advanced",
        "Music: Guitar - Private",
        "Music: Guitar - Tri Private",
        "Music: Keyboard",
        "Music: Keyboard - Advanced",
        "Music: Keyboard - Private",
        "Music: Keyboarding",
        "Music: Piano",
        "Music: Piano - Advanced",
        "Music: Piano - Private",
        "Music: Singing",
        "Music: Singing - Private",
        "Music: Ukulele - Private",
        "Music: Violin - Private",
        "Musical Theatre",
        "Stroke Improvement",
        "Stroke Improvement - Small Group",
    ],
    "Skating & Ice Programs": [
        "Hockey Skills",
        "Learn To Skate - Advanced",
        "Learn To Skate - Beginner",
        "Learn To Skate - Beginner - Small Group",
        "Learn to Skate 1",
        "Learn to Skate 2",
        "Learn to Skate 3",
        "Learn to Skate 4",
        "Learn to Skate 5",
        "Skateboarding: Instructional",
    ],
    "Social & Community Programs": [
        "Cards: Bridge Progressive",
        "Club (Girls)",
        "Club: Dungeons and Dragons",
        "Club: Reading",
        "Club: Social",
        "Girls Club",
    ],
    "Sports & Games": [
        "Advanced Kickboxing",
        "Aikido - Advanced",
        "Aikido - Beginner",
        "Arnis/Kali - Advanced",
        "Arnis/Kali - Beginner",
        "Badminton",
        "Badminton: Instructional",
        "Badminton: Recreational",
        "Ball Hockey: Instructional",
        "Ball Hockey: Recreational",
        "Balls and Bells",
        "Baseball: House League",
        "Baseball: Instructional",
        "Basketball",
        "Basketball: House League",
        "Basketball: Instructional",
        "Basketball: Instructional (Boys)",
        "Basketball: Instructional (Girls)",
        "Basketball: Recreational",
        "Basketball: Recreational (Men)",
        "Basketball: Recreational (Women)",
        "Cardio: Kickboxing",
        "Cheerleading",
        "Clinic: Tennis - Hitting Spin Shots",
        "Clinic: Tennis - Reading Plays & Ball Direction",
        "Club: Chess",
        "Cricket",
        "Cricket: Instructional",
        "Cycling Tour de France",
        "Cycling: Instructional-Beginner",
        "Dance: Ballet",
        "Dance: Ballet with Showcase",
        "Dance: Ballroom",
        "Dance: Ballroom - Advanced",
        "Dance: Ballroom Latin",
        "Dodgeball: Instructional",
        "Dodgeball: Recreational",
        "First Tee Golf",
        "Flag Football: Instructional",
        "Games",
        "Games, Partners and Teamwork",
        "Games: Billiards (Women)",
        "Games: Board",
        "Games: Chess",
        "Games: Chess - Intermediate",
        "Games: Dungeons & Dragons",
        "Golf - Private",
        "Golf: Instructional",
        "Golf: Recreational",
        "Gymnastics",
        "Gymnastics - Advanced",
        "Gymnastics - Beginner",
        "Gymnastics - Intermediate",
        "Gymnastics: Competitive",
        "Gymnastics: Tumbling",
        "Gymnastics: Tumbling - Beginner",
        "Gymnastics: Tumbling - Intermediate",
        "HDA Ball Hockey",
        "HDA Ball Hockey - Referral",
        "HIIT: Balance Ball",
        "Hapkido - Advanced",
        "Hapkido - Beginner",
        "House of Hockey Ball Hockey",
        "Intro to Kickboxing",
        "Karate - Advanced",
        "Karate - Beginner",
        "Karate - Beginner (Women)",
        "Karate: Hapkido - Beginner",
        "Karate: Hapkido - Intermediate",
        "Lacrosse: Instructional",
        "Martial Arts",
        "Martial Arts - Advanced",
        "Martial Arts - Beginner",
        "Multi-Sport: Instructional",
        "Multi-Sport: Instructional (Girls)",
        "Multi-Sport: Recreational",
        "Noodle Gym",
        "Outdoor Soccer: Instructional",
        "Philpott Tennis",
        "Pickleball (2SLGBTQ+)",
        "Pickleball: Instructional",
        "Pickleball: Instructional - Intermediate",
        "Pickleball: Recreational",
        "Racket Sports",
        "Rhythmic Gymnastics",
        "Self Defence (Women)",
        "Self Defence - Advanced",
        "Self Defence - Beginner",
        "Soccer: House League",
        "Soccer: Instructional",
        "Soccer: Recreational",
        "Table Tennis: Instructional",
        "Table Tennis: Recreational",
        "Tae Kwon Do",
        "Tae Kwon Do - Advanced",
        "Tae Kwon Do - Beginner",
        "Tae Kwon Do - Beginner (Girls)",
        "Tae Kwon Do with Belts",
        "Tennis - Private",
        "Tennis - Semi Private",
        "Tennis - Small Group",
        "Tennis: Instructional",
        "Tennis: Instructional - Advanced",
        "Tennis: Instructional - Advanced - Small Group",
        "Tennis: Instructional - Beginner",
        "Tennis: Instructional - Intermediate",
        "Tennis: Instructional - Intermediate - Small Group",
        "Tennis: Recreational",
        "Toronto Women's Softball: House League B Division",
        "Toronto Women's Softball: House League Ball Busters",
        "Toronto Women's Softball: House League Cherry Bombs",
        "Toronto Women's Softball: House League Hustlers",
        "Toronto Women's Softball: House League Kstangs",
        "Toronto Women's Softball: House League Wild Pitches",
        "Toronto Women's Softball: House League Wreckers",
        "Volleyball: Instructional",
        "Volleyball: Instructional (Girls)",
        "Volleyball: Recreational",
        "Workshop: Build a Wooden Recycling Truck",
        "Workshop: Dance - Ballet",
    ],
    "Swimming & Aquatics": [
        "Adult Swim 1",
        "Adult Swim 1 (Women)",
        "Adult Swim 1 - Small Group",
        "Adult Swim 2",
        "Adult Swim 2 (Women)",
        "Adult Swim 2 - Small Group",
        "Adult Swim 3",
        "Adult Swim 3 (Women)",
        "Adult Swim 3 - Small Group",
        "Aquatic Fitness Conference and Instructor Certification",
        "Aquatic Fitness Conference and Instructor Recertification",
        "Aquatic Fitness Instructor Certification",
        "Aquatic Fitness Instructor: Specialty - Mind and Body",
        "Aquatic Fitness Instructor: Specialty - Water Walking",
        "Aquatic Supervisor",
        "Bronze Cross",
        "Bronze Cross & Intermediate First Aid with CPR-C & AED",
        "Bronze Cross (Girls)",
        "Bronze Cross Challenge Exam",
        "Bronze Cross Recert",
        "Bronze Cross and Intermediate First Aid with CPR-C & AED",
        "Bronze Cross and Standard First Aid (CPR C)",
        "Bronze Medallion",
        "Bronze Medallion & Basic First Aid CPR C & AED",
        "Bronze Medallion & Emergency First Aid (CPR B)",
        "Bronze Medallion and Emergency First Aid (CPR B)",
        "Bronze Medallion and Emergency First Aid (CPR B) (Girls)",
        "Bronze Medallion, Bronze Cross & Intermediate First Aid with",
        "Bronze Star",
        "Bronze Star and Basic First Aid (CPR A)",
        "Challenge Swim: Bronze",
        "Challenge Swim: Gold",
        "Challenge Swim: Silver",
        "Circuit Training",
        "Creative Cueing",
        "Equipment Overload Circuits",
        "Examiner Course",
        "Future Lifeguards",
        "Guardian Swim 1",
        "Guardian Swim 1 (Boys)",
        "Guardian Swim 1 (Girls)",
        "Guardian Swim 2",
        "Guardian Swim 2 (Girls)",
        "Guardian Swim 3",
        "Guardian Swim 3 (Girls)",
        "H2O Flow",
        "High Intensity Interval Training",
        "Indigenous Lens Swim Lessons",
        "Instructor Recert Course",
        "Jump, Punch, Kick and Jab!",
        "Junior Lifeguard Club",
        "Kick up your Combo's",
        "Kickboxing/TaeKwon Aqua Theory",
        "Mentorship with Moxy 2",
        "Mentorship with Moxy!",
        "National Lifeguard - Pool",
        "National Lifeguard - Pool Recert",
        "National Lifeguard - Waterfront Core",
        "National Lifeguard - Waterfront Recert",
        "Older Adult Swim 1",
        "Painting: Water Colour",
        "Painting: Watercolour",
        "Painting: Watercolour - Advanced",
        "Pedagogical Practice",
        "Pool Attendant",
        "Pool Operator - Level 1",
        "Pool Operator - Level 2",
        "Pottery",
        "Pottery: Sculpture",
        "Pottery: Wheel",
        "Ranger Patrol",
        "Rookie Patrol",
        "Rookie/Ranger/Star Patrol Combined",
        "SPLASH Swim Team",
        "Splash Team Class",
        "Splash Team Class – Winter Olympics",
        "Sports Training the Watergym of the Future",
        "Star Patrol",
        "Swim Clinic: Back Crawl - Beginner",
        "Swim Clinic: Beginner",
        "Swim Clinic: Floats and Glides",
        "Swim Clinic: Front Crawl - Intermediate",
        "Swim Clinic: Introduction to Water",
        "Swim Clinic: Junior Lifesaving Sport",
        "Swim Clinic: Strokes - Legs/Kicking Techniques",
        "Swim Clinic: Surface Support and Treading Water",
        "Swim Clinic: Waterfront Junior Lifesaving Sport",
        "Swim Fit",
        "Swim Lessons - Private",
        "Swim Lessons - Private (Girls)",
        "Swim Lessons - Semi Private",
        "Swim Lessons - Semi-Private",
        "Swim and Lifesaving Instructor",
        "Swim to Survive",
        "Synchronized Swimming: Girls",
        "Ultra Swim 1",
        "Ultra Swim 1 (ATR)",
        "Ultra Swim 1 (Boys)",
        "Ultra Swim 1 (Girls)",
        "Ultra Swim 1 (Women)",
        "Ultra Swim 1 - Small Group",
        "Ultra Swim 2",
        "Ultra Swim 2 (ATR)",
        "Ultra Swim 2 (Boys)",
        "Ultra Swim 2 (Girls)",
        "Ultra Swim 2 (Women)",
        "Ultra Swim 2 - Small Group",
        "Ultra Swim 2 - Small Group (Girls)",
        "Ultra Swim 3",
        "Ultra Swim 3 (ATR)",
        "Ultra Swim 3 (Boys)",
        "Ultra Swim 3 (Girls)",
        "Ultra Swim 3 - Semi Private",
        "Ultra Swim 3 - Small Group",
        "Ultra Swim 3 - Small Group (Girls)",
        "Ultra Swim 4",
        "Ultra Swim 4 (ATR)",
        "Ultra Swim 4 (Boys)",
        "Ultra Swim 4 (Girls)",
        "Ultra Swim 4 - Small Group",
        "Ultra Swim 4 - Small Group (Girls)",
        "Ultra Swim 5",
        "Ultra Swim 5 (ATR)",
        "Ultra Swim 5 (Boys)",
        "Ultra Swim 5 (Girls)",
        "Ultra Swim 5 - Semi Private",
        "Ultra Swim 5 - Small Group",
        "Ultra Swim 5 - Small Group (Girls)",
        "Ultra Swim 6",
        "Ultra Swim 6 (ATR)",
        "Ultra Swim 6 (Girls)",
        "Ultra Swim 6 - Small Group",
        "Ultra Swim 7",
        "Ultra Swim 7 (Boys)",
        "Ultra Swim 7 (Girls)",
        "Ultra Swim 7 - Small Group",
        "Ultra Swim 8",
        "Ultra Swim 8 (Girls)",
        "Ultra Swim 8 - Small Group",
        "Ultra Swim 9",
        "Ultra Swim 9 (Girls)",
        "Ultra Swim 9 - Small Group",
        "Ultra Youth 1 (ATR Daytime)",
        "Ultra Youth Swim 1",
        "Ultra Youth Swim 1 (ATR)",
        "Ultra Youth Swim 1 (Boys)",
        "Ultra Youth Swim 1 (Girls)",
        "Ultra Youth Swim 2",
        "Ultra Youth Swim 2 (Girls)",
        "Ultra Youth Swim 3",
        "WaterArt Acronym",
        "Waterpolo",
        "Workshop: Painting: Watercolour",
        "Workshop: Watercolour - Colour Theory",
        "Workshop: Watercolour - Dry-on-Dry",
        "Workshop: Watercolour - Lifting/Blotting",
        "Workshop: Watercolour - Masking",
        "Workshop: Watercolour - Salt Technique",
        "Workshop: Watercolour - Splattering",
        "Workshop: Watercolour - Wet-On-Wet",
        "Workshop: Watercolour - Wet-on-Wet",
    ],
}

REGISTERED_TITLE_TO_CATEGORY = {
    title: category
    for category, titles in REGISTERED_CATEGORY_TO_TITLES.items()
    for title in titles
}

OTHER_REGISTERED_CATEGORY = "Other Programs"
